my:
  name: demo

#Determines the timeout in milliseconds until a connection is established.
app:
  template:
    request-timeout: 60000
    connect-timeout: 60000
    socket-timeout: 60000
    max-request-connection: 1000
    max-request-connection-per-route: 200

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    com:
      example: TRACE
    org:
      springframework: ERROR
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} | %-5level | %X{CORRELATION_ID} | %c{1} | %msg%n"

springdoc:
  server:
    url: http://localhost:8080
  api-docs:
    enabled: true
    path: /api-doc
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger
    groups-order: asc

spring:
  application:
    name: demo
  elasticsearch:
    uris: 127.0.0.1:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
